# Generated by Django 6.0.6 on 2026-07-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='summary_is_outdated',
            field=models.BooleanField(default=False),
        ),
    ]
